@host = http://localhost
@port = 8000

### ADMINISTRADOR OBTIENE UN USUARIO POR ID
GET {{host}}:{{port}}/users/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VycyI6NCwicm9sZSI6ImFkbWluIiwiZXhwaXJlIjoxNzcwODIzMzIyfQ.qC-cVXAj6TnZGMHUj1TKStxrW7dm548aRoIPfJ8j6Dc

### ADMINISTRADOR OBTIENE TODOS LOS OPERARIOS
GET {{host}}:{{port}}/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VycyI6NCwicm9sZSI6ImFkbWluIiwiZXhwaXJlIjoxNzcwODIzMzIyfQ.qC-cVXAj6TnZGMHUj1TKStxrW7dm548aRoIPfJ8j6Dc

### REGISTER
POST {{host}}:{{port}}/auth/register
Content-Type: application/json

{
    "name": "Julian",
    "surname": "Perez",
    "mail": "pepa@gmail.com",
    "password": "123456",
    "role": "user"
}

### ADMINISTRADOR REGISTRA UNA CUENTA
POST {{host}}:{{port}}/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VycyI6NCwicm9sZSI6ImFkbWluIiwiZXhwaXJlIjoxNzcwODIzMzIyfQ.qC-cVXAj6TnZGMHUj1TKStxrW7dm548aRoIPfJ8j6Dc
Content-Type: application/json

{
    "name": "Mario",
    "surname": "Perez",
    "mail": "pepa@gmail.com",
    "password": "123456",
    "role": "user"
}

### LOGIN
POST {{host}}:{{port}}/auth/login
Content-Type: application/json

{
    "mail": "eliagaliana@gmail.com",
    "password": "123456"
}


### ADMINISTRADOR ACTUALIZA UNA CUENTA DE OPERARIO
PUT {{host}}:{{port}}/users/8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VycyI6NCwicm9sZSI6ImFkbWluIiwiZXhwaXJlIjoxNzcwODI1MDU5fQ.d627NMelZkv0bnJEk-KTfLUvBGybiHuXfEXnKzIrfZU


{
    "name": "Paco"
}


### ADMINISTRADOR BORRA UNA CUENTA DE OPERARIO
DELETE {{host}}:{{port}}/users/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VycyI6NCwicm9sZSI6ImFkbWluIiwiZXhwaXJlIjoxNzcwODI0MzE2fQ.3sXNBPQaFkre8aJBYxGSQMXi-26luTAngf1CxrVxMxE

### ADMINISTRADOR OBTIENE UN USUARIO POR CORREO
GET {{host}}:{{port}}/users/mail/eli
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VycyI6NCwicm9sZSI6ImFkbWluIiwiZXhwaXJlIjoxNzcwODIzMzIyfQ.qC-cVXAj6TnZGMHUj1TKStxrW7dm548aRoIPfJ8j6Dc

