@host = http://empresadeconstruccion-empresaconstruccion.e.aivencloud.com
@port = 10156

### obtener un usuario por id 
GET {{{{host}}:{{port}}}}/user/

### obtener todos usuarios
GET {{{{host}}:{{port}}}}/user/

### crear un nuevo usuario
PORT {{host}}: {{port}}/auth/register
Content-Type: application/json

{
    "name": "Andrea",
    "surname": "Heredia",
    "mail": "andrea.heredia@gmail.com",
    "password_hash": "123456",
    "role": "admin"
}