@host = http://127.0.0.1
@port = 8000

### obtener un usuario por id 
GET http://127.0.0.1:8000/users/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VycyI6MTYsInJvbGUiOiJhZG1pbiIsImV4cGlyZSI6MTc3MTI3MTc4OX0.t5v_qHafBYUPiIo0KR1BoxldfHL-jd5PnvB1cNUT4WM

### obtener todos usuarios
GET {{host}}:{{port}}/user/


### obtener todos usuarios
PUT {{host}}:{{port}}/users/8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VycyI6MTYsInJvbGUiOiJhZG1pbiIsImV4cGlyZSI6MTc3MTI3MjIzOX0.FM4yqNsnsjiqkPfndTfPqzdnbQNZYhf52P1Bxmf2rV8

{
    "name": "Paco",
    "surname": "Sanchez",
    "mail": "don_paco@gmail.com",
    "password": "123456",
    "role": "user"
}


### crear un nuevo usuario
POST {{host}}:{{port}}/auth/register
Content-Type: application/json

{
    "name": "Elia",
    "surname": "Galiana",
    "mail": "eliagaliana@gmail.com",
    "password": "XXXX1234",
    "role": "admin"
}
### iniciar sesión para obtener token
POST http://127.0.0.1:8000/auth/login
Content-Type: application/json

{
    "mail": "eliagaliana@gmail.com",
    "password": "123456"
}

### Guardar el token de respuesta para usarlo abajo (Authorization: Bearer <TOKEN>)

### CREAR OBRA (Requiere Admin) => OK, funciona
POST http://127.0.0.1:8000/constructions/
Content-Type: application/json
Authorization: Bearer TOKEN

{
    "name": "Obra Prueba Backend",
    "description": "Edificio residencial centro",
    "address": "Calle Mayor 1",
    "latitude": 40.416,
    "longitude": -3.703
}

### ACTUALIZAR OBRA (PARCIAL - SOLO NOMBRE) => OK, funciona

PUT http://127.0.0.1:8000/constructions/2
Content-Type: application/json
Authorization: Bearer TOKEN

{
    "name": "Obra Prueba Backend (Renombrada)"
}

### OBTENER TODAS LAS OBRAS => OK, funciona
GET http://127.0.0.1:8000/constructions/
Authorization: Bearer TOKEN

### CREAR ASIGNACION (Para probar Log luego) => OK, funciona. Nota: no se puede asignar un operario a una obra si no hay un admin asignado a esa obra
POST http://127.0.0.1:8000/assignments/
Content-Type: application/json
Authorization: Bearer TOKEN

{
    "users_id": 1,  
    "constructionsSites_id": 2, 
    "date_start": "2025-01-01",
    "date_finish": "2026-04-01"
}

### CREAR LOG (COMO OPERARIO) => OK, funciona 
# Usar el token del usuario asignado 
POST http://127.0.0.1:8000/logs/
Content-Type: application/json
Authorization: Bearer TOKEN

{
    "description": "Operario que no esta asignado intenta crear log",
    "type": "Operario Alerta SEGURIDAD",
    "constructionsSites_id": 3
}